### ISSUE TITLE
Issues loading other epub books

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/who-is-that#32]
I've tried to load other books, e.g Alice's Adventures in Wonderland from [here](https://gutenberg.org/ebooks/11) and only the title is loaded but not text, as shown in this screen shot:

<img width="1457" alt="Screenshot 2024-06-12 at 17 11 09" src="https://github.com/alan-turing-institute/who-is-that/assets/11162074/4133360c-a206-438f-88cb-bc7938fe7655">

**Comment by radka-j** [comment]
It looks like the book isn't organised in chapters so we need to update extraction to allow for this scenario.

**Comment by jemrobinson** [comment]
Should be an easy fix - most books don't use `epub-type:chapter` which we currently select on. If we remove that requirement it should work for all books.

**Comment by radka-j** [comment]
Alice in Wonderland uses `class:chapter` so there might be other ways to get the data by chapter. Otherwise we can just return the full text.

**Comment by crangelsmith** [comment]
I've tried with 100 years of solitude from [here](https://archive.org/details/OneHundredYearsOfSolitude_201710).

And I get this error: 
<img width="1076" alt="Screenshot 2024-06-13 at 10 18 16" src="https://github.com/alan-turing-institute/who-is-that/assets/11162074/0aec7de7-a38e-47e1-8566-4afe9d9d5264">

**Comment by radka-j** [comment]
There are quite a few books that at the moment don't show any text:
- A case of Sherlock Holmes
- A doll's house
- RUR
- bunch of Shakespeare plays

Also, Dracula only loads letters in the book and no other text.
